jaymzh/sugarjar

bin/sj
lib/sugarjar/commands.rb
lib/sugarjar/config.rb
lib/sugarjar/util.rb

Some fixes from trying to use this at work:
* don't assume the ruby to run under
* don't crash when no subcommands are passed in
* don't assume paths for hub/git
* fix crash for unknown method
* fix handling of empty config files

Various minor fixes

---

bin/sj

It's unreliable and catches other errors in confusing ways.
Instead use `public_methods` to find methods and match.

Stop rescuing NoMethodError as a way of fallthru

---

lib/sugarjar/commands.rb

Closes #28
When the user's branch was created not by us, it often has the wrong
tracked branch. Fix that.

Handle wrong tracked branch better

---

lib/sugarjar/commands.rb

Closes #37
When doing `bcleanall`, we shouldn't land on a random branch. It should
either be where we started, or master.

bcleanall: Return to reasonable branch

---

.rubocop.yml
README.md
bin/sj
lib/sugarjar/commands.rb

While GitHub provides a way to specify a pull-request template by putting the
right file into a repo, there is no way to tell git to automatically pick up a
commit template by dropping a file in the repo. Users must do something like:
`git config commit.template <file>`. Making each developer do this is error
prone, so this setting will automatically set this up for each developer.
* Adds `commit_template` to repoconfig option
* Fixes minor issue where logging level wasn't set as early
as it should be
* Sets an option for the "fake" initialization of SugarJar::Commands
so we don't touch the repo until we're ready
Closes #38

Introducing automatic commit template configuration

---

.rubocop.yml
lib/sugarjar/commands.rb
lib/sugarjar/config.rb
spec/commands_spec.rb

A user who clones-and-forks an https repo they don't have commit
access to, still wants their forked repo to be using SSH so they
can push to it and make PRs.
In addition, we were misparsing repo paths in a variety of different
ways, so this centralizes that parsing into two methods, uses them
consistently, and then unittests them in a variety of cases.
This closes #56

Always use SSH for forked remote; handle various repo paths better

---

lib/sugarjar/util.rb

When using http(s) remotes git can prompt, and we need to handle that
appropriately.
Closes #52

Handle git prompts for usernames

---

.rubocop.yml
bin/sj
lib/sugarjar/commands.rb

Add a new `smartpullrequest` command (aliases: `spr` and `smartpr`).
It's a shortcut for `hub pull-request`, but checks for a dirty repo
first.
That closes #51
Since we have a dirty check now, this adds it to `smartpush` and
`forcepush` as well as refactors those to DRY them up a bit.
Finally, this adds `--ignore-dirty` and `--ignore-prerun-failure` to
allow bypassing botht he new dirty check and the existing prerun checks.

Add smartpr; add dirty checks in {s,f}push

---

.sugarjar.yaml
lib/sugarjar/commands.rb

For each linter, if the repo becomes dirty, prompt the user to amend
or quit.
This solves the problem where today users can be confused if a linter
fixes something but errors and the user doesn't get a clear
understanding, or when it changes something, but doesn't error and
what we push isn't in the repo.
Output looks like this:
```shell
[phil@rider (betterlint) RVM(2.7.1) sugarjar]$ ./bin/sj lint
[lint] scripts/run_rubocop.sh: Corrected
WARN: The linter modified the repo. Here's the diff:
diff --git a/lib/sugarjar/commands.rb b/lib/sugarjar/commands.rb
index d350b54..d9c9491 100644
--- a/lib/sugarjar/commands.rb
+++ b/lib/sugarjar/commands.rb
@@ -405,7 +405,7 @@ class SugarJar
SugarJar::Log.info('Exiting at user request.')
exit(1)
when /^a/
-                qamend("-a")
+ …
```

Better support for autocorrecting linters

---

lib/sugarjar/util.rb

This closes #73
Catch "anonymous access denied" when git tries to use http access
without auth.

Handle anonymous auth failers

---

lib/sugarjar/commands.rb
spec/commands_spec.rb

`hub` will default to `https` when giving a shortname, but that can
lead to prompting for credentials, so always use SSH unless otherwise
specified.
This closes #72

Force SSH protocol unless otherwise specified

---

lib/sugarjar/commands.rb

We always assumed github.com for canonicalization instead of honoring
`--github-host`. This fixes that.

Fix canonicalization

---

RELEASE_PROCESS.md
omnibus/.kitchen.yml
omnibus/config/projects/sugarjar.rb

* move back to ruby 2.7.1 - only thing that seems to build on centos
* add centos 8 and ubuntu 20.04 to releases we build
* update release instructions to auto-cleanup kitchen instances

Various fixes to releasing

---

bin/sj

In #89, @infcted exposed a bug in our parsing. We check to see if any
naked arguments in the command-line are valid SJ subcommands, and one
could have that, but it be an arg to an option, and then when we figure
out our real sub-command, it turns out it's not valid.
This changes that to actually validate our subcommand is valid once we
have it so that this doesn't happen.
Closes #89

Improve parsing for subcommands

---

.github/workflows/lint.yml
.github/workflows/unit.yml
lib/sugarjar/config.rb
packaging/README.md

The rubocop action we used was broken and deprecated.
Found another, but had issues (see comments in workflow file).
In the meantime do it manually.

Fixing lint

---

.sugarjar.yaml
README.md
lib/sugarjar/commands.rb
scripts/get_linters

It is not uncommon to want to discover the linters or unit tests to be
run dynamically. A common example is deciding the linters based on the
files that were modified.
This PR implements two new configs in the Repository Configuration:
`lint_list_cmd` and `unit_list_cmd` which are a command to run which
will return the linters/unit tests to run.
This also moves our linters to `lint_list_cmd`.
Closes #80.

Implement check lister-commands

---

lib/sugarjar/commands.rb

Handle 'version' better when using `gh`

---

.github/workflows/lint.yml
.github/workflows/unit.yml
CHANGELOG.md
lib/sugarjar/version.rb

changelog, version info, etc.
Plus cleanup versions of ruby that lint/unit run on.

Prep version 0.0.11

---

README.md
bin/sj

* The README has the old env variable for setting log level
* The help didn't mention the aforementioned variable
* The defaults for options in the help were inconsistently documented.

Fix up some minor doc issues

---

bin/sj

If there's no subcommand detected, print out help instead of crashing.
Closes #123

Handle no-subcommand better

---

spec/commands_spec.rb

For Ruby packages, Debian autopkgtest runs in an environment where `gem2deb-test-runner` removes the `lib` directory from the source tree, so the specs have to be able to load the installed copy instead.
With this change, `lib` gets added to the front of the path, and the relative `require` is changed to not specify a path. So when specs are run from a source tree checkout the `lib` in the checkout is still preferred, but if it's not available the installed library gets used to satisfy the `require`.
See https://wiki.debian.org/Teams/Ruby/Packaging/Tests#Case_eight:_autopkgtest_failure
Signed-off-by: Michel Alexandre Salim <michel@michel-slm.name>

Allow commands_spec to be run against the installed copy of sugarjar

---

README.md

Repology does not index PPAs, so point Ubuntu users to michel-slm's PPA for now.
Signed-off-by: Michel Alexandre Salim <michel@michel-slm.name>

Reference the Ubuntu PPA

---

bin/sj
lib/sugarjar/commands.rb
spec/commands_spec.rb

This adds a new feature, feature prefixes, which will create all
features with a prefix, which is useful in branch-based workflows
where developers are expected to create all branches with a specific
prefix like "$USER/".

New feature: feature prefixes

---

README.md
bin/sj
lib/sugarjar/commands.rb
lib/sugarjar/config.rb

This adds an `auto` option to `github_cli`, and makes it default to
`gh`.
It also cleans up some additional README stuff.

Support for automatically determining GitHub cli to use

---

README.md
RELEASE_PROCESS.md
packaging/README.md

* Fix image in README
* Some release-process notes to myself

Several minor doc tweaks

---

README.md
lib/sugarjar/commands.rb
lib/sugarjar/repoconfig.rb
spec/repoconfig_spec.rb
sugarjar.gemspec

* Add support for `include_from` and `overwrite_from` in
repoconfig
* Add support for featureprefix to `co`
* Allow relative paths for linters and unittests
* Smartpr now uses `--fill` when utilizing `gh`

featureprefix, linter, smartpr fixes

---

spec/commands_spec.rb
spec/repoconfig_spec.rb

These should always have been `../lib`.

Fix the LOAD_PATH dirs for the specs

---

lib/sugarjar/util.rb
packaging/README.md

* Add missing `require` to `util.rb` - this works fine today in
the app, but only because the main code already includes
`mixlib/shellout`
* Update release instructions for Fedora

Minor cleanups

---

.github/workflows/lint.yml
.github/workflows/unit.yml
.rubocop.yml
sugarjar.gemspec

When I did ruby cleanups I dropped everything that wasn't in "normal
maintenance", but that causes issues for some Distros that lag behind
on their ruby updates. So we'll allow up through security maintenance,
which means adding back 3.0.
Also, start testing on 3.3.

Relax ruby requirements

---

Gemfile.lock
lib/sugarjar/commands.rb

Sometimes `git` will detect a rebase will fail and will abort it
for us. If this happens, when we try to abort, it'll fail. Detect
this case and don't abort if `git` already did.

Fix aborted rebases

---

bin/sj
lib/sugarjar/commands.rb
lib/sugarjar/config.rb

* If > 1 commit exists, don't pass in --fill
* Add a new option to allow people to opt-out of --fill in all cases
* Tell people when we are autofilling
Closes #152

SPR: don't autofill when more than one commit exists

---

lib/sugarjar/commands.rb

In some cases, specifically in `sj up`, we might double-prefix
a branch name. This unifies the logic and then checks for that.

Fix feature prefixing

---

lib/sugarjar/commands.rb

Make sure to set the tracked branch when creating features
so that `sj up` works as expected.

sj-feature: set tracked branch

---

lib/sugarjar/commands.rb

Fix pull-suggestions diff

---

lib/sugarjar/commands.rb

When the parent branch goes away, set the tracking to 'most_main'

Handle parent feature going away

---

CHANGELOG.md
Gemfile.lock
lib/sugarjar/commands.rb
lib/sugarjar/version.rb

* changelog
* bundle update
* new rubocop
* new version

Version bump

---

lib/sugarjar/commands.rb

It turns out there's a somewhat magical syntax for `gh`'s `--head` option, but if you get it right, you can prevent it from pushing, or changing the tracked branch, or prompting.

Update `gh` usage to prevent pushes and prompts

---

bin/sj
lib/sugarjar/commands.rb

* If on a forked repo, note that we cannot stack PRs
* Use `--fill-first` when needed

Cleanup stacked PR handling

---

lib/sugarjar/commands/amend.rb
lib/sugarjar/commands/bclean.rb
lib/sugarjar/commands/branch.rb
lib/sugarjar/commands/checks.rb
lib/sugarjar/commands/feature.rb
lib/sugarjar/commands/pullsuggestions.rb
lib/sugarjar/commands/push.rb
lib/sugarjar/commands/smartpullrequest.rb
lib/sugarjar/commands/up.rb
lib/sugarjar/repoconfig.rb
lib/sugarjar/util.rb
spec/commands_spec.rb

* We were checking to see if we could stack PRs based on comparing
the name of the upstream with the org of the push which.. are never
the same, so compare the actual orgs
* Rename a few functions to fit with ruby standard naming
* Add a simple unit test

Fix subfeature PR creation; plus some cleanups

---

lib/sugarjar/commands.rb
lib/sugarjar/commands/bclean.rb

When a branch is checked out as a worktree, you cannot switch to it.
As such we need to skip them when doing bclean{,all}.
Closes #195

bclean: Handle worktrees gracefully
