jaymzh/sugarjar

.gitignore
.rubocop.yml
Gemfile
RELEASE_PROCESS.md
bin/sj
omnibus/.kitchen.local.yml
omnibus/.kitchen.yml
omnibus/Berksfile
omnibus/Gemfile
omnibus/README.md
omnibus/config/projects/sugarjar.rb
omnibus/config/software/sugarjar.rb
omnibus/omnibus.rb
omnibus/package-scripts/sugarjar/postinst
omnibus/package-scripts/sugarjar/postrm
omnibus/package-scripts/sugarjar/preinst
omnibus/package-scripts/sugarjar/prerm
sugarjar.gemspec

* 'sj' was never defined as an executable in the gem, oops
* Add Gemfile to the gem, needed for appbundle
* Omnibus package and software definition
* Move test stuff out of gemspec and into Gemfile
* Stop using `gemspec` in Gemfile and instead use `gem "sugarjar", path:
"."` - no idea what the difference is, but required for omnibus

Add omnibus support

---

bin/sj
lib/sugarjar/commands.rb
lib/sugarjar/config.rb

In order to fix option parsing in #22 we moved the creation of the
`SugarJar::Commands` object to before we finished parsing options.
While that's necessary, we need to re-create it *after* option parsing
for options to have an effect (obviously).
This fixes that. It also fixes the default GH user setting and adds
a bit of debugging.

Fix enterprise github

---

.github/workflows/lint.yml

Make the lint workflow have one job per check

---

lib/sugarjar/commands.rb

Just added this, but it shouldn't trigger on master.

Fix over-aggressive warning

---

lib/sugarjar/commands.rb

Fix crash due to typo

---

lib/sugarjar/util.rb

Closes #39
If a user doesn't use `hub`, then they won't have an auth token,
and `sj` just fails in awkward ways.

Handle case where `hub` has no auth token

---

omnibus/.gitignore
omnibus/.kitchen.yml

* put the whole repo into omnibus kitchens
* Missing lock ignore from git

Two minor omnibus fixes

---

omnibus/README.md

Basically what I submitted here: https://github.com/chef/omnibus/pull/951

Update omnibus docs

---

lib/sugarjar/commands.rb

Fix #7 for real: variable not string.

Fix typo in #43

---

.github/workflows/lint.yml
.github/workflows/unit.yml
Gemfile
lib/sugarjar/commands.rb
scripts/lint
scripts/run_rspec.sh
scripts/unit
spec/commands_spec.rb

* Fix `sj unit` to run unittests instead of lints
* Add unittests for set_commit_template
* Setup our SJ config to know about unittests
* Add GH Actions for unittests

Add unittests

---

.github/workflows/lint.yml
.rubocop.yml
omnibus/config/projects/sugarjar.rb
omnibus/config/software/sugarjar.rb
sugarjar.gemspec

Move to new version of rubocop action

---

bin/sj

Signed-off-by: Jaldert Rombouts <jaldert@vicarious.com>

Fix typo: verson -> version.

---

bin/sj
lib/sugarjar/commands.rb

New smartlog feature that imitates FB's "sl" extension.
Also drop useless newline and preserve color.

Add new smartlog feature; add color to binfo

---

.github/ISSUE_TEMPLATE/bug_report.md
.mdl_style.rb
.rubocop.yml
.sugarjar.yaml
bin/sj
lib/sugarjar/commands.rb
lib/sugarjar/util.rb
lib/sugarjar/version.rb
omnibus/Gemfile
sugarjar.gemspec

Huge overhaul of our putput to be much friendlier.
* Important bits are not colorized
* Success/Failure now in green/red
* Messages shortened for clarity
* Split out link messages by link script
* Fix lint with args
* Update our lint

Colorize and simplify output

---

RELEASE_PROCESS.md
omnibus/.kitchen.yml
omnibus/config/projects/sugarjar.rb

* debian 10
* fix maintainer
* ruby 2.7.2

Some minor fixes for releases

---

packaging/Vagrantfile
rubygem-sugarjar.spec

* binary package should be called `sugarjar`
* depend on hub and git

Fix RPM spec

---

rubygem-sugarjar.spec

I'll probably end up pulling all this once I get dist-git for SJ, but
for now I need a place to put this stuff.

More spec fixes

---

rubygem-sugarjar.spec

Another Spec fix

---

lib/sugarjar/commands.rb

Rebase failures often ended up in confusing messages that don't tell
users how to get out of the mess. This catches those errors and gives
users pointers.
If it fails in `sj up`, we leave the repo as-is and give the user both
the revert option or the fix option and all the output:
```
$ sj up
FATAL: cookbook_for_mac: Failed to rebase on upstream/master. Leaving the repo as-is. You can get out of this with a `git rebase --abort`. Output from failed rebase is:
STDOUT:
First, rewinding head to replay your work on top of it...
Applying: Mucking about
Using index info to reconstruct a base tree...
M	cookbooks/<redacted>/recipes/macos.rb
Falling back to patching base and 3-way merge...
Auto-merging cookbooks/<redacted>/recipes/macos.rb
CONFLICT (content): Merge conflict in …
```

Fix rebase issues

---

lib/sugarjar/commands.rb

In #90 @marc-sensenich points out a case where SAML errors cause us
to think we have a fork when we actually don't. Detect this explicitly
and handle it nicely.
Closes #90

Handle SAML errors better

---

lib/sugarjar/commands.rb

Handle slashes in branch names

---

.rubocop.yml
README.md
bin/sj
lib/sugarjar/commands.rb
lib/sugarjar/config.rb
lib/sugarjar/util.rb

`hub` is unofficial and not very maintained these days. Meanwhile, 'gh'
has reached maturity. This adds initial support for the `gh` cli, and
makes it configurable.
Closes #110

Support for the `gh` cli

---

README.md
bin/sj
lib/sugarjar/commands.rb

This is a first pass at a helper to pull in suggestions from the GH UI.
Closes #86.

Implement command to get remote suggestions

---

lib/sugarjar/commands.rb

As repos are moving the primary branch from `master` to `main`, it can
leave some odd pitfalls for people. Lets try to make this process easier
by catching it and providing guidance.
Closes #114.

Handle mis-matched primary branch names

---

lib/sugarjar/commands.rb

Bugfix in 16b97aec73c1eb169be6b6403dcee017968e3cc9, somehow.
Plus fix newer lint.

Minor fixes

---

lib/sugarjar/commands.rb

Currently if we 'sclone' a repo in our own personal org, we'll crash
because `gh fork` will fail. This handles that case properly.

gh: Handle sclone of our own repos

---

README.md
bin/sj

Point people to Sapling now that it is out.

Point people to sappling

---

README.md

Update notice about sapling

---

bin/sj
lib/sugarjar/commands.rb

* Add new 'subfeature' command to create subfeatures
* Update 'feature' to properly handle a base branch
* Fix warning message about bad tracked branches
* Update help message to include arguments
Closes #151

add subfeature support

---

README.md

Add docs on subfeature and stacked PRs

---

lib/sugarjar/commands.rb

When using `gh pr create`, the tracked branch gets munged, so lets
set it back.
While we're at it, give the user some more guidance.

Fix 'gh' branch mangling

---

Gemfile.lock

One last round before we release.

Bundler update; gem updates

---

CHANGELOG.md
Gemfile.lock
lib/sugarjar/version.rb

version 1.1.3 bump

---

packaging/README-fedora.md
packaging/Vagrantfile
packaging/provision.sh

Various fedora packaging tweaks

---

lib/sugarjar/commands.rb

Fix 'smartlog' when on detached head

---

.github/workflows/lint.yml
.github/workflows/unit.yml
README.md

Add docs for 2.0 beta release

---

.github/workflows/lint.yml
.github/workflows/unit.yml
sugarjar.gemspec

fix metadata URL; tests on 2.0-devel branch

---

sugarjar.gemspec

Fix metadata URL

---

README.md
examples/sample_repoconfig.yaml

More docs cleanup

---

.github/workflows/lint.yml
.github/workflows/unit.yml

Now that branches are switching for 2.0 release, cleanup
workflow files.

Cleaning up workflows

---

CHANGELOG.md
Gemfile.lock
lib/sugarjar/version.rb
sugarjar.gemspec

Published 2.0.0 gem missing files

Version 2.0.1 bump

---

spec/commands/feature_spec.rb
spec/repoconfig_spec.rb

Make unittests work outside of git repos
